name: Fantasy Hockey Daily Analysis

on:
  # Run daily at 3am EDT (7am UTC)
  schedule:
    - cron: '0 7 * * *'

  # Allow manual trigger with dry run option
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Dry run (skip committing changes)'
        required: false
        type: boolean
        default: true

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Install dependencies
        run: uv sync --frozen

      - name: Create .env file from secrets
        run: |
          cat > .env << EOF
          YAHOO_CLIENT_ID=${{ secrets.YAHOO_CLIENT_ID }}
          YAHOO_CLIENT_SECRET=${{ secrets.YAHOO_CLIENT_SECRET }}
          YAHOO_ACCESS_TOKEN_JSON='${{ secrets.YAHOO_ACCESS_TOKEN_JSON }}'
          LEAGUE_ID=${{ vars.LEAGUE_ID }}
          TEAM_ID=${{ vars.TEAM_ID }}
          GAME_KEY=${{ vars.GAME_KEY }}
          ANTHROPIC_API_KEY=${{ secrets.ANTHROPIC_API_KEY }}
          EMAIL_FROM=${{ secrets.EMAIL_FROM }}
          EMAIL_TO=${{ secrets.EMAIL_TO }}
          EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}
          SMTP_SERVER=${{ vars.SMTP_SERVER }}
          SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}
          SMTP_PORT=${{ vars.SMTP_PORT }}
          EOF

      - name: Run Fantasy Hockey Agent
        run: |
          if [ "${{ inputs.dry_run }}" = "true" ]; then
            uv run fantasy_hockey_agent.py --dry-run
          else
            uv run fantasy_hockey_agent.py
          fi

      - name: Commit and push changes
        if: inputs.dry_run != true
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/recommendations_history.json
          git commit -m "chore: add $(date +'%Y-%m-%d') recommendations history" || echo "No changes to commit"
          git push
